version: '3.5'
services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      VK_TOKEN: ${VK_TOKEN}
      VK_GROUP_ID: ${VK_GROUP_ID}
      BOT_DATABASE: ${BOT_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
